export const GET_LESSONS_REQUEST = 'GET_LESSONS_REQUEST'
export const GET_LESSONS_SUCCESS = 'GET_LESSONS_SUCCESS'
export const GET_LESSONS_FAIL = 'GET_LESSONS_FAIL'

export const CREATE_LESSON_REQUEST = 'CREATE_LESSON_REQUEST'
export const CREATE_LESSON_SUCCESS = 'CREATE_LESSON_SUCCESS'
export const CREATE_LESSON_FAIL = 'CREATE_LESSON_FAIL'
export const CREATE_LESSON_RESET = 'CREATE_LESSON_RESET'

export const LESSON_DETAILS_REQUEST = 'LESSON_DETAILS_REQUEST'
export const LESSON_DETAILS_SUCCESS = 'LESSON_DETAILS_SUCCESS'
export const LESSON_DETAILS_FAIL = 'LESSON_DETAILS_FAIL'

export const UPDATE_LESSON_REQUEST = 'UPDATE_LESSON_REQUEST'
export const UPDATE_LESSON_SUCCESS = 'UPDATE_LESSON_SUCCESS'
export const UPDATE_LESSON_FAIL = 'UPDATE_LESSON_FAIL'
export const UPDATE_LESSON_RESET = 'UPDATE_LESSON_RESET'

export const DELETE_LESSON_REQUEST = 'DELETE_LESSON_REQUEST'
export const DELETE_LESSON_SUCCESS = 'DELETE_LESSON_SUCCESS'
export const DELETE_LESSON_FAIL = 'DELETE_LESSON_FAIL'
