export const GET_USER_LESSONS_REQUEST = 'GET_USER_LESSONS_REQUEST'
export const GET_USER_LESSONS_SUCCESS = 'GET_USER_LESSONS_SUCCESS'
export const GET_USER_LESSONS_FAIL = 'GET_USER_LESSONS_FAIL'

export const CREATE_USER_LESSON_REQUEST = 'CREATE_USER_LESSON_REQUEST'
export const CREATE_USER_LESSON_SUCCESS = 'CREATE_USER_LESSON_SUCCESS'
export const CREATE_USER_LESSON_FAIL = 'CREATE_USER_LESSON_FAIL'
export const CREATE_USER_LESSON_RESET = 'CREATE_USER_LESSON_RESET'

export const USER_LESSON_DETAILS_REQUEST = 'USER_LESSON_DETAILS_REQUEST'
export const USER_LESSON_DETAILS_SUCCESS = 'USER_LESSON_DETAILS_SUCCESS'
export const USER_LESSON_DETAILS_FAIL = 'USER_LESSON_DETAILS_FAIL'

export const MULTI_USER_LESSON_DETAILS_REQUEST =
  'MULTI_USER_LESSON_DETAILS_REQUEST'
export const MULTI_USER_LESSON_DETAILS_SUCCESS =
  'MULTI_USER_LESSON_DETAILS_SUCCESS'
export const MULTI_USER_LESSON_DETAILS_FAIL = 'MULTI_USER_LESSON_DETAILS_FAIL'

export const UPDATE_USER_LESSON_REQUEST = 'UPDATE_USER_LESSON_REQUEST'
export const UPDATE_USER_LESSON_SUCCESS = 'UPDATE_USER_LESSON_SUCCESS'
export const UPDATE_USER_LESSON_FAIL = 'UPDATE_USER_LESSON_FAIL'
export const UPDATE_USER_LESSON_RESET = 'UPDATE_USER_LESSON_RESET'

export const DELETE_USER_LESSON_REQUEST = 'DELETE_USER_LESSON_REQUEST'
export const DELETE_USER_LESSON_SUCCESS = 'DELETE_USER_LESSON_SUCCESS'
export const DELETE_USER_LESSON_FAIL = 'DELETE_USER_LESSON_FAIL'
